name: Deploy Website via VPN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Connect to Tailscale VPN
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ""
          oauth-secret: ""
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      # 2. Checkout repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 3. Deploy to Server via SSH over Tailscale VPN
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/my-website
            git pull origin main
